version: '3'

services:
  minio1:
    image: minio/minio
    command: server /export
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_DISABLE_API_KEY: 'true'
    ports:
      - "9000:9000"
    volumes:
      - /mnt/minio-storage:/export
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.hostname == minio1
    networks:
      - storage_network

  minio2:
    image: minio/minio
    command: server /export
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_DISABLE_API_KEY: 'true'
    ports:
      - "9000:9000"
    volumes:
      - /mnt/minio-storage:/export
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.hostname == minio2
    networks:
      - storage_network

  minio3:
    image: minio/minio
    command: server /export
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_DISABLE_API_KEY: 'true'
    ports:
      - "9000:9000"
    volumes:
      - /mnt/minio-storage:/export
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.hostname == minio3
    networks:
      - storage_network

  prometheus:
    image: prom/prometheus
    volumes:
      - /path/on/host/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /path/on/host/data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - storage_network
  grafana:
    image: grafana/grafana
    volumes:
      - /path/on/host/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - storage_network

networks:
  storage_network:
    driver: overlay
