version: '2'

services:
  zookeeper:
    image: bitnami/zookeeper
    hostname: zookeeper-1
    container_name: zookeeper-1
    volumes:
      - ./data:/bitnami/zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    extra_hosts:
      - "zookeeper-1:10.1.1.1"
      - "zookeeper-2:10.1.1.2"
      - "kafka-1:10.1.1.3"
      - "kafka-2:10.1.1.4"
      - "kafka-3:10.1.1.5"
    environment:
      - ZOO_MY_ID=<zookeeper-id>
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_PORT=2181
      - ZOO_SERVERS=server.1=<zookeeper-1>:2888:3888 server.2=<zookeeper-2>:2888:3888
  