version: '3'

services:
  kafka:
    image: bitnami/kafka
    hostname: kafka-1
    container_name: kafka-1
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
    - ./data:/bitnami/kafka
    extra_hosts:
      - "zookeeper-1:10.1.1.1"
      - "zookeeper-2:10.1.1.2"
      - "kafka-1:10.1.1.3"
      - "kafka-2:10.1.1.4"
      - "kafka-3:10.1.1.5"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=<zookeeper-1>:2181,<zookeeper-2>:2182
      - KAFKA_CFG_BROKER_ID=<kafka-id>
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://<kafka-hostname>:9092