---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "api.telbiz.la:10.1.1.11"
      - "payment.telbiz.la:10.1.1.11"
      - "wallet.telbiz.la:10.1.1.11"
      - "topup.telbiz.la:10.1.1.11"
      - "sms.telbiz.la:10.1.1.11"
      - "data.telbiz.la:10.1.1.11"
      - "tenant.telbiz.la:10.1.1.11"
      - "log.telbiz.la:10.1.1.11"
      - "app.telbiz.la:10.1.1.11"
      - "schedule.telbiz.la:10.1.1.11"
      - "job.telbiz.la:10.1.1.11"
      - "vas.telbiz.la:10.1.1.11"
  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    hostname: broker
    extra_hosts:
      - "api.telbiz.la:10.1.1.11"
      - "payment.telbiz.la:10.1.1.11"
      - "wallet.telbiz.la:10.1.1.11"
      - "topup.telbiz.la:10.1.1.11"
      - "sms.telbiz.la:10.1.1.11"
      - "data.telbiz.la:10.1.1.11"
      - "tenant.telbiz.la:10.1.1.11"
      - "log.telbiz.la:10.1.1.11"
      - "app.telbiz.la:10.1.1.11"
      - "schedule.telbiz.la:10.1.1.11"
      - "job.telbiz.la:10.1.1.11"
      - "vas.telbiz.la:10.1.1.11"
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1